name: Hello # ワークフロー名
on: push # イベント
jobs: # ジョブ
  hello: # ジョブ名
    runs-on: ubuntu-latest # ランナー
    env:
      PASSWORD: ${{ secrets.SYSTEM_PASSWORD}}
    steps: # ステップ
      - run: echo "${PASSWORD}" # シェルコマンド
      - uses: actions/checkout@v4 # アクション
